// <auto-generated />
using System;
using API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200129155841_SQLite Migrations")]
    partial class SQLiteMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catgories");
                });

            modelBuilder.Entity("API.Models.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EditField")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EditMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ingrident1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingrident2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingrident3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingrident4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingrident5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingrident6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
